package com.selvina.entity;
// Generated Feb 15, 2018 8:40:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Barang generated by hbm2java
 */
public class Barang  implements java.io.Serializable {


     private String idBarang;
     private Kategori kategori;
     private String namaBarang;
     private float harga;
     private int stok;
     private Set<DetailPenjualan> detailPenjualans = new HashSet<DetailPenjualan>(0);

    public Barang() {
    }

	
    public Barang(String idBarang, Kategori kategori, String namaBarang, float harga, int stok) {
        this.idBarang = idBarang;
        this.kategori = kategori;
        this.namaBarang = namaBarang;
        this.harga = harga;
        this.stok = stok;
    }
    public Barang(String idBarang, Kategori kategori, String namaBarang, float harga, int stok, Set<DetailPenjualan> detailPenjualans) {
       this.idBarang = idBarang;
       this.kategori = kategori;
       this.namaBarang = namaBarang;
       this.harga = harga;
       this.stok = stok;
       this.detailPenjualans = detailPenjualans;
    }
   
    public String getIdBarang() {
        return this.idBarang;
    }
    
    public void setIdBarang(String idBarang) {
        this.idBarang = idBarang;
    }
    public Kategori getKategori() {
        return this.kategori;
    }
    
    public void setKategori(Kategori kategori) {
        this.kategori = kategori;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public float getHarga() {
        return this.harga;
    }
    
    public void setHarga(float harga) {
        this.harga = harga;
    }
    public int getStok() {
        return this.stok;
    }
    
    public void setStok(int stok) {
        this.stok = stok;
    }
    public Set<DetailPenjualan> getDetailPenjualans() {
        return this.detailPenjualans;
    }
    
    public void setDetailPenjualans(Set<DetailPenjualan> detailPenjualans) {
        this.detailPenjualans = detailPenjualans;
    }




}


