package com.selvina.entity;
// Generated Feb 15, 2018 8:40:48 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Kategori generated by hbm2java
 */
public class Kategori  implements java.io.Serializable {


     private String idKategori;
     private String namaKategori;
     private Set<Barang> barangs = new HashSet<Barang>(0);

    public Kategori() {
    }

	
    public Kategori(String idKategori, String namaKategori) {
        this.idKategori = idKategori;
        this.namaKategori = namaKategori;
    }
    public Kategori(String idKategori, String namaKategori, Set<Barang> barangs) {
       this.idKategori = idKategori;
       this.namaKategori = namaKategori;
       this.barangs = barangs;
    }
   
    public String getIdKategori() {
        return this.idKategori;
    }
    
    public void setIdKategori(String idKategori) {
        this.idKategori = idKategori;
    }
    public String getNamaKategori() {
        return this.namaKategori;
    }
    
    public void setNamaKategori(String namaKategori) {
        this.namaKategori = namaKategori;
    }
    public Set<Barang> getBarangs() {
        return this.barangs;
    }
    
    public void setBarangs(Set<Barang> barangs) {
        this.barangs = barangs;
    }




}


