package com.selvina.entity;
// Generated Feb 15, 2018 8:40:48 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Penjualan generated by hbm2java
 */
public class Penjualan  implements java.io.Serializable {


     private String idPenjualan;
     private Date tanggalPenjualan;
     private float totalHarga;
     private Set<DetailPenjualan> detailPenjualans = new HashSet<DetailPenjualan>(0);

    public Penjualan() {
    }

	
    public Penjualan(String idPenjualan, Date tanggalPenjualan, float totalHarga) {
        this.idPenjualan = idPenjualan;
        this.tanggalPenjualan = tanggalPenjualan;
        this.totalHarga = totalHarga;
    }
    public Penjualan(String idPenjualan, Date tanggalPenjualan, float totalHarga, Set<DetailPenjualan> detailPenjualans) {
       this.idPenjualan = idPenjualan;
       this.tanggalPenjualan = tanggalPenjualan;
       this.totalHarga = totalHarga;
       this.detailPenjualans = detailPenjualans;
    }
   
    public String getIdPenjualan() {
        return this.idPenjualan;
    }
    
    public void setIdPenjualan(String idPenjualan) {
        this.idPenjualan = idPenjualan;
    }
    public Date getTanggalPenjualan() {
        return this.tanggalPenjualan;
    }
    
    public void setTanggalPenjualan(Date tanggalPenjualan) {
        this.tanggalPenjualan = tanggalPenjualan;
    }
    public float getTotalHarga() {
        return this.totalHarga;
    }
    
    public void setTotalHarga(float totalHarga) {
        this.totalHarga = totalHarga;
    }
    public Set<DetailPenjualan> getDetailPenjualans() {
        return this.detailPenjualans;
    }
    
    public void setDetailPenjualans(Set<DetailPenjualan> detailPenjualans) {
        this.detailPenjualans = detailPenjualans;
    }




}


