package com.selvina.entity;
// Generated Feb 15, 2018 8:40:48 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String password;
     private String namaLengkap;
     private String noTelepon;
     private String alamat;

    public User() {
    }

    public User(String username, String password, String namaLengkap, String noTelepon, String alamat) {
       this.username = username;
       this.password = password;
       this.namaLengkap = namaLengkap;
       this.noTelepon = noTelepon;
       this.alamat = alamat;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNamaLengkap() {
        return this.namaLengkap;
    }
    
    public void setNamaLengkap(String namaLengkap) {
        this.namaLengkap = namaLengkap;
    }
    public String getNoTelepon() {
        return this.noTelepon;
    }
    
    public void setNoTelepon(String noTelepon) {
        this.noTelepon = noTelepon;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


